-- Swarm Wallet — Snowflake schema (run in Worksheets or: npm run snowflake:migrate)
-- Replace SWARM_WALLET / APP / COMPUTE_WH if your account uses different names.

CREATE DATABASE IF NOT EXISTS SWARM_WALLET;
CREATE SCHEMA IF NOT EXISTS SWARM_WALLET.APP;
USE SCHEMA SWARM_WALLET.APP;

CREATE TABLE IF NOT EXISTS SEARCHES (
  SEARCH_ID        VARCHAR PRIMARY KEY,
  QUERY_TEXT       VARCHAR NOT NULL,
  PRODUCT_KEY      VARCHAR NOT NULL,
  PRODUCT          VARCHAR,
  CATEGORY         VARCHAR,
  STARTED_AT       TIMESTAMP_NTZ,
  COMPLETED_AT     TIMESTAMP_NTZ,
  DURATION_MS      NUMBER,
  AGENT_COUNT      NUMBER,
  FINDING_COUNT    NUMBER,
  STATUS           VARCHAR,
  ERROR_MESSAGE    VARCHAR,
  PLAN_JSON        VARIANT,
  REPLAY_URLS      VARIANT,
  QUERY_EMBEDDING  VECTOR(FLOAT, 768)
);

CREATE TABLE IF NOT EXISTS AGENT_EVENTS (
  EVENT_ID         VARCHAR DEFAULT UUID_STRING() PRIMARY KEY,
  SEARCH_ID        VARCHAR NOT NULL,
  AGENT_ID         VARCHAR,
  SITE             VARCHAR,
  ROLE             VARCHAR,
  STATUS           VARCHAR,
  CURRENT_URL      VARCHAR,
  ERROR_MESSAGE    VARCHAR,
  RECORDED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS FINDINGS (
  FINDING_ID       VARCHAR DEFAULT UUID_STRING() PRIMARY KEY,
  SEARCH_ID        VARCHAR NOT NULL,
  AGENT_ID         VARCHAR,
  PRODUCT_KEY      VARCHAR NOT NULL,
  SITE             VARCHAR,
  ROLE             VARCHAR,
  NAME             VARCHAR,
  PRICE            NUMBER(12,2),
  SOURCE           VARCHAR,
  URL              VARCHAR,
  HIGHLIGHT        VARCHAR,
  CONFIDENCE       FLOAT,
  IS_OUTLIER       BOOLEAN DEFAULT FALSE,
  OUTLIER_REASON   VARCHAR,
  REPLAY_URL       VARCHAR,
  RECORDED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  TEXT_FOR_EMBED   VARCHAR,
  FINDING_EMBEDDING VECTOR(FLOAT, 768)
);

CREATE TABLE IF NOT EXISTS VERDICTS (
  SEARCH_ID        VARCHAR PRIMARY KEY,
  RECOMMENDATION   VARCHAR,
  TOP_PICKS        VARIANT,
  CAUTION          VARCHAR,
  TIMING           VARCHAR,
  WAREHOUSE_INSIGHTS VARIANT,
  RECORDED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE DYNAMIC TABLE IF NOT EXISTS PRODUCT_PRICE_DAILY
  TARGET_LAG = '1 hour'
  WAREHOUSE = COMPUTE_WH
  AS
  SELECT
    PRODUCT_KEY,
    SITE,
    DATE_TRUNC('day', RECORDED_AT) AS PRICE_DAY,
    MIN(PRICE) AS MIN_PRICE,
    MAX(PRICE) AS MAX_PRICE,
    AVG(PRICE) AS AVG_PRICE,
    COUNT(*) AS OBSERVATION_COUNT
  FROM FINDINGS
  WHERE PRICE IS NOT NULL
  GROUP BY PRODUCT_KEY, SITE, DATE_TRUNC('day', RECORDED_AT);

CREATE OR REPLACE VIEW SITE_RELIABILITY AS
  SELECT
    SITE,
    ROLE,
    COUNT(*) AS SAMPLE_SIZE,
    AVG(IFF(STATUS IN ('done'), 1, 0)) AS SUCCESS_RATE
  FROM AGENT_EVENTS
  WHERE RECORDED_AT >= DATEADD(day, -30, CURRENT_TIMESTAMP())
  GROUP BY SITE, ROLE
  HAVING COUNT(*) >= 3;

CREATE OR REPLACE VIEW PRODUCT_PRICE_STATS AS
  SELECT
    PRODUCT_KEY,
    COUNT(*) AS OBSERVATION_COUNT,
    MIN(PRICE) AS MIN_PRICE_90D,
    MAX(PRICE) AS MAX_PRICE_90D,
    AVG(PRICE) AS AVG_PRICE_90D,
    STDDEV(PRICE) AS STDDEV_PRICE_90D,
    DATEDIFF('day', MIN(RECORDED_AT), CURRENT_TIMESTAMP()) AS DAYS_OF_HISTORY
  FROM FINDINGS
  WHERE PRICE IS NOT NULL
    AND RECORDED_AT >= DATEADD(day, -90, CURRENT_TIMESTAMP())
  GROUP BY PRODUCT_KEY;

CREATE OR REPLACE VIEW COLLECTIVE_BEST_SITE AS
  SELECT
    PRODUCT_KEY,
    SITE,
    AVG(PRICE) AS AVG_PRICE,
    COUNT(*) AS SAMPLES,
    ROW_NUMBER() OVER (
      PARTITION BY PRODUCT_KEY
      ORDER BY AVG(PRICE) ASC, COUNT(*) DESC
    ) AS PRICE_RANK
  FROM FINDINGS
  WHERE PRICE IS NOT NULL
    AND RECORDED_AT >= DATEADD(day, -60, CURRENT_TIMESTAMP())
  GROUP BY PRODUCT_KEY, SITE;
